### PR TITLE
Fix: Remove unnecessary GitHub Workflow Files

### PR DESCRIPTION
**Pull request by amos-kibet**
- fix: remove unnecessary imports
- fix: adjust valid user password to 4 chars long
- fix: format code
- fix: remove IO.inspect
- chore(deps): add credo dep
- fix: format code
- fix(tmp): comment out whole code
- fix: adjust password for failing tests
- fix(tmp): comment out whole code
- fix: remove unnecessary workflow files

### CODE REVIEW

**Comment by amos-kibet** [comment]
deploy branch now has one workflow, that we should configure to deploy whenever we pull from master. What do you think @cheropChirchir7963 ?

**Comment by cheropChirchir7963** [comment]
> deploy branch now has one workflow, that we should configure to deploy whenever we pull from master. What do you think @cheropChirchir7963 ?

Good idea I like...

**Comment by amos-kibet** [comment]
Oooh, yeah. My bad, I did not check out from master branch. I will have to remind myself to do this always, I forget.

**Comment by amos-kibet** [comment]
You can just approve. I will observe that next time.

**Review by cheropChirchir7963 — APPROVED** [review]

**Pull request merged**
